import 'package:flutter/material.dart';

enum AppFeatureStatus { available, partial, planned }

enum AppFeatureControl {
  themeMode,
  rakshakMode,
  shakeSos,
  voiceSos,
  autoRecordAudio,
  autoRecordVideo,
  aiDetection,
  aiAutoAlert,
  checkInInterval,
  notifications,
}

class AppFeature {
  final String id;
  final String title;
  final String subtitle;
  final String category;
  final IconData icon;
  final Color gradientStart;
  final Color gradientEnd;
  final String artKey;
  final AppFeatureStatus status;
  final String details;
  final String? routeName;
  final AppFeatureControl? control;

  const AppFeature({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.category,
    required this.icon,
    required this.gradientStart,
    required this.gradientEnd,
    required this.artKey,
    required this.status,
    required this.details,
    this.routeName,
    this.control,
  });
}

class AppFeatures {
  static const List<String> categories = [
    'Emergency / SOS',
    'Live Safety Tracking',
    'AI Detection Features',
    'Fake Protection Features',
    'Nearby Help Features',
    'Contacts / Network',
    'Evidence & Security',
    'Women Safety Support',
    'App / User Features',
    'Smart Connectivity',
    'Future Features',
  ];

  static const List<AppFeature> all = [
    AppFeature(
      id: 'one_tap_sos',
      title: 'One-tap SOS',
      subtitle: 'Immediate emergency trigger from the dashboard.',
      category: 'Emergency / SOS',
      icon: Icons.sos_rounded,
      gradientStart: Color(0xFFD7263D),
      gradientEnd: Color(0xFF7A1424),
      artKey: 'sos',
      status: AppFeatureStatus.available,
      details: 'The app already has a dedicated SOS screen with a countdown and emergency dispatch flow.',
      routeName: '/sos',
    ),
    AppFeature(
      id: 'panic_mode_sos',
      title: 'Panic mode SOS',
      subtitle: 'Dedicated panic escalation flow.',
      category: 'Emergency / SOS',
      icon: Icons.warning_rounded,
      gradientStart: Color(0xFFB5179E),
      gradientEnd: Color(0xFF7209B7),
      artKey: 'sos',
      status: AppFeatureStatus.partial,
      details: 'The current SOS flow acts like panic mode, but there is not yet a separate advanced panic profile.',
      routeName: '/sos',
    ),
    AppFeature(
      id: 'send_live_location_during_sos',
      title: 'Send live location during SOS',
      subtitle: 'Attach location when an SOS is triggered.',
      category: 'Emergency / SOS',
      icon: Icons.share_location_rounded,
      gradientStart: Color(0xFF277DA1),
      gradientEnd: Color(0xFF184E77),
      artKey: 'liveLocation',
      status: AppFeatureStatus.partial,
      details: 'Current SOS includes current location. Continuous live streaming after SOS still needs backend workflow support.',
    ),
    AppFeature(
      id: 'alert_emergency_contacts',
      title: 'Alert emergency contacts',
      subtitle: 'Notify trusted contacts right away.',
      category: 'Emergency / SOS',
      icon: Icons.contacts_rounded,
      gradientStart: Color(0xFFF72585),
      gradientEnd: Color(0xFFB5179E),
      artKey: 'contacts',
      status: AppFeatureStatus.partial,
      details: 'Emergency contact data exists and SOS emits alerts, but full contact delivery reliability still depends on backend integration.',
      routeName: '/contacts',
    ),
    AppFeature(
      id: 'continuous_tracking_after_sos',
      title: 'Continuous tracking after SOS',
      subtitle: 'Keep sharing movement after distress.',
      category: 'Emergency / SOS',
      icon: Icons.track_changes_rounded,
      gradientStart: Color(0xFFF28482),
      gradientEnd: Color(0xFFBC4749),
      artKey: 'liveLocation',
      status: AppFeatureStatus.planned,
      details: 'This needs a dedicated post-SOS background tracking workflow and backend watch session.',
    ),
    AppFeature(
      id: 'loud_siren_alarm',
      title: 'Loud siren / alarm',
      subtitle: 'Draw attention immediately.',
      category: 'Emergency / SOS',
      icon: Icons.campaign_rounded,
      gradientStart: Color(0xFFF3722C),
      gradientEnd: Color(0xFFC44536),
      artKey: 'sos',
      status: AppFeatureStatus.planned,
      details: 'No siren playback flow exists yet.',
    ),
    AppFeature(
      id: 'flashlight_strobe',
      title: 'Flashlight strobe',
      subtitle: 'Use strobe light in emergencies.',
      category: 'Emergency / SOS',
      icon: Icons.flashlight_on_rounded,
      gradientStart: Color(0xFFF9C74F),
      gradientEnd: Color(0xFFF8961E),
      artKey: 'sos',
      status: AppFeatureStatus.planned,
      details: 'This still needs flashlight plugin support and emergency-mode UX.',
    ),
    AppFeature(
      id: 'hidden_stealth_sos',
      title: 'Hidden / stealth SOS',
      subtitle: 'Trigger help discreetly.',
      category: 'Emergency / SOS',
      icon: Icons.visibility_off_rounded,
      gradientStart: Color(0xFF4D908E),
      gradientEnd: Color(0xFF264653),
      artKey: 'sos',
      status: AppFeatureStatus.planned,
      details: 'A stealth trigger needs a disguised interaction pattern and protected execution flow.',
    ),
    AppFeature(
      id: 'shake_phone_sos',
      title: 'Shake phone trigger',
      subtitle: 'Shake to launch SOS quickly.',
      category: 'Emergency / SOS',
      icon: Icons.vibration_rounded,
      gradientStart: Color(0xFF9D4EDD),
      gradientEnd: Color(0xFF5A189A),
      artKey: 'sos',
      status: AppFeatureStatus.available,
      details: 'Shake detection is wired to the SOS flow and is configurable in Settings.',
      control: AppFeatureControl.shakeSos,
    ),
    AppFeature(
      id: 'voice_command_sos',
      title: 'Voice command SOS',
      subtitle: 'Trigger SOS with help words.',
      category: 'Emergency / SOS',
      icon: Icons.keyboard_voice_rounded,
      gradientStart: Color(0xFF4361EE),
      gradientEnd: Color(0xFF3A0CA3),
      artKey: 'sos',
      status: AppFeatureStatus.available,
      details: 'Voice command listening is integrated and can be enabled in Settings.',
      control: AppFeatureControl.voiceSos,
    ),
    AppFeature(
      id: 'realtime_location',
      title: 'Real-time live location',
      subtitle: 'Share your moving position live.',
      category: 'Live Safety Tracking',
      icon: Icons.location_on_rounded,
      gradientStart: Color(0xFF2A9D8F),
      gradientEnd: Color(0xFF1D3557),
      artKey: 'liveLocation',
      status: AppFeatureStatus.available,
      details: 'Live location sharing screen is already available in the app.',
      routeName: '/live_location',
    ),
    AppFeature(
      id: 'follow_me_mode',
      title: 'Follow Me mode',
      subtitle: 'Keep guardians watching in real time.',
      category: 'Live Safety Tracking',
      icon: Icons.directions_walk_rounded,
      gradientStart: Color(0xFF43AA8B),
      gradientEnd: Color(0xFF277DA1),
      artKey: 'liveLocation',
      status: AppFeatureStatus.partial,
      details: 'Current live location covers the core idea, but there is no dedicated Follow Me journey state yet.',
      routeName: '/live_location',
    ),
    AppFeature(
      id: 'safe_journey_mode',
      title: 'Safe Journey mode',
      subtitle: 'Structured safety journey with watchers.',
      category: 'Live Safety Tracking',
      icon: Icons.alt_route_rounded,
      gradientStart: Color(0xFF90BE6D),
      gradientEnd: Color(0xFF2D6A4F),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'Safe Journey screen already supports starting, checking in, and ending a journey.',
      routeName: '/safe_journey',
    ),
    AppFeature(
      id: 'journey_start_end_tracking',
      title: 'Journey start/end tracking',
      subtitle: 'Log protected journey sessions.',
      category: 'Live Safety Tracking',
      icon: Icons.route_rounded,
      gradientStart: Color(0xFF52B788),
      gradientEnd: Color(0xFF2D6A4F),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'Journey provider supports start and arrived-safe events.',
      routeName: '/safe_journey',
    ),
    AppFeature(
      id: 'checkin_timer',
      title: 'Check-in timer',
      subtitle: 'Prompt regular safety check-ins.',
      category: 'Live Safety Tracking',
      icon: Icons.timer_rounded,
      gradientStart: Color(0xFF8ECAE6),
      gradientEnd: Color(0xFF219EBC),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'Check-in interval is implemented and configurable in Settings.',
      routeName: '/safe_journey',
      control: AppFeatureControl.checkInInterval,
    ),
    AppFeature(
      id: 'auto_alert_no_checkin',
      title: 'Auto alert if no check-in',
      subtitle: 'Escalate if the user goes silent.',
      category: 'Live Safety Tracking',
      icon: Icons.notification_important_rounded,
      gradientStart: Color(0xFFFFD166),
      gradientEnd: Color(0xFFEF476F),
      artKey: 'journey',
      status: AppFeatureStatus.planned,
      details: 'The timer exists, but missed check-in escalation still needs automatic backend alert logic.',
    ),
    AppFeature(
      id: 'go_private_mode',
      title: 'Go Private mode',
      subtitle: 'Pause sharing when needed.',
      category: 'Live Safety Tracking',
      icon: Icons.lock_rounded,
      gradientStart: Color(0xFF577590),
      gradientEnd: Color(0xFF355070),
      artKey: 'liveLocation',
      status: AppFeatureStatus.planned,
      details: 'A private-mode safety state is not wired yet.',
    ),
    AppFeature(
      id: 'private_safety_network',
      title: 'Private safety network',
      subtitle: 'Share only with selected trusted people.',
      category: 'Live Safety Tracking',
      icon: Icons.groups_rounded,
      gradientStart: Color(0xFF4CC9F0),
      gradientEnd: Color(0xFF4895EF),
      artKey: 'contacts',
      status: AppFeatureStatus.partial,
      details: 'Trusted contacts and watchers exist, but a separate private network management flow is still limited.',
      routeName: '/contacts',
    ),
    AppFeature(
      id: 'route_monitoring',
      title: 'Route monitoring',
      subtitle: 'Watch progress along a route.',
      category: 'Live Safety Tracking',
      icon: Icons.map_rounded,
      gradientStart: Color(0xFF48CAE4),
      gradientEnd: Color(0xFF0077B6),
      artKey: 'journey',
      status: AppFeatureStatus.planned,
      details: 'Destination entry exists, but route deviation monitoring is not implemented yet.',
    ),
    AppFeature(
      id: 'eta_tracking',
      title: 'ETA tracking',
      subtitle: 'Estimate arrival and monitor delay.',
      category: 'Live Safety Tracking',
      icon: Icons.schedule_rounded,
      gradientStart: Color(0xFF00B4D8),
      gradientEnd: Color(0xFF0077B6),
      artKey: 'journey',
      status: AppFeatureStatus.planned,
      details: 'ETA computation still needs route services and backend timing logic.',
    ),
    AppFeature(
      id: 'scream_detection',
      title: 'Scream detection',
      subtitle: 'Detect possible audible distress.',
      category: 'AI Detection Features',
      icon: Icons.record_voice_over_rounded,
      gradientStart: Color(0xFFFF6B6B),
      gradientEnd: Color(0xFFC9184A),
      artKey: 'tips',
      status: AppFeatureStatus.available,
      details: 'Basic scream detection heuristics exist in the AI detection service.',
      control: AppFeatureControl.aiDetection,
    ),
    AppFeature(
      id: 'panic_movement_detection',
      title: 'Panic movement detection',
      subtitle: 'Detect unusual rapid movement patterns.',
      category: 'AI Detection Features',
      icon: Icons.directions_run_rounded,
      gradientStart: Color(0xFFFF9770),
      gradientEnd: Color(0xFFFF6D00),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'Movement heuristics exist as part of the AI detection service.',
      control: AppFeatureControl.aiDetection,
    ),
    AppFeature(
      id: 'fall_detection',
      title: 'Fall detection',
      subtitle: 'Detect sudden fall-like motion.',
      category: 'AI Detection Features',
      icon: Icons.personal_injury_rounded,
      gradientStart: Color(0xFFFFC857),
      gradientEnd: Color(0xFFFF7B00),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'The AI detection service already contains fall detection logic.',
      control: AppFeatureControl.aiDetection,
    ),
    AppFeature(
      id: 'abnormal_motion_detection',
      title: 'Abnormal motion detection',
      subtitle: 'Flag high-risk unusual motion.',
      category: 'AI Detection Features',
      icon: Icons.motion_photos_on_rounded,
      gradientStart: Color(0xFFF4A261),
      gradientEnd: Color(0xFFE76F51),
      artKey: 'journey',
      status: AppFeatureStatus.available,
      details: 'Abnormal movement detection exists in the AI detection service.',
      control: AppFeatureControl.aiDetection,
    ),
    AppFeature(
      id: 'silent_distress_detection',
      title: 'Silent distress detection',
      subtitle: 'Detect subtle non-verbal distress signals.',
      category: 'AI Detection Features',
      icon: Icons.psychology_alt_rounded,
      gradientStart: Color(0xFF8338EC),
      gradientEnd: Color(0xFF3A0CA3),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'This would need stronger sensor fusion and behavioral analysis than the current heuristics.',
    ),
    AppFeature(
      id: 'ai_risk_alerts',
      title: 'AI risk detection alerts',
      subtitle: 'Prompt or auto-alert on detected danger.',
      category: 'AI Detection Features',
      icon: Icons.smart_toy_rounded,
      gradientStart: Color(0xFF3F37C9),
      gradientEnd: Color(0xFF560BAD),
      artKey: 'tips',
      status: AppFeatureStatus.available,
      details: 'AI danger alerts and auto-alert behavior are already exposed via Settings.',
      control: AppFeatureControl.aiAutoAlert,
    ),
    AppFeature(
      id: 'unsafe_inactivity_detection',
      title: 'Unsafe inactivity detection',
      subtitle: 'Spot risky silence or stillness.',
      category: 'AI Detection Features',
      icon: Icons.hourglass_bottom_rounded,
      gradientStart: Color(0xFF577590),
      gradientEnd: Color(0xFF3D405B),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'This still needs background monitoring and inactivity rules.',
    ),
    AppFeature(
      id: 'instant_fake_call',
      title: 'Instant fake call',
      subtitle: 'Quick escape-call launch.',
      category: 'Fake Protection Features',
      icon: Icons.call_rounded,
      gradientStart: Color(0xFF4361EE),
      gradientEnd: Color(0xFF3A0CA3),
      artKey: 'fakeCall',
      status: AppFeatureStatus.partial,
      details: 'The screen exists, but the real fake incoming call experience is still a placeholder.',
      routeName: '/fake_call',
    ),
    AppFeature(
      id: 'scheduled_fake_call',
      title: 'Scheduled fake call',
      subtitle: 'Set a delayed fake incoming call.',
      category: 'Fake Protection Features',
      icon: Icons.schedule_send_rounded,
      gradientStart: Color(0xFF4D96FF),
      gradientEnd: Color(0xFF3F37C9),
      artKey: 'fakeCall',
      status: AppFeatureStatus.planned,
      details: 'Scheduling logic still needs implementation.',
    ),
    AppFeature(
      id: 'fake_incoming_screen',
      title: 'Fake incoming caller screen',
      subtitle: 'Show a realistic fake caller UI.',
      category: 'Fake Protection Features',
      icon: Icons.smartphone_rounded,
      gradientStart: Color(0xFF90E0EF),
      gradientEnd: Color(0xFF3A86FF),
      artKey: 'fakeCall',
      status: AppFeatureStatus.planned,
      details: 'A realistic callkit-style incoming screen is not wired yet.',
    ),
    AppFeature(
      id: 'escape_call_mode',
      title: 'Escape call mode',
      subtitle: 'Dedicated exit scenario call workflow.',
      category: 'Fake Protection Features',
      icon: Icons.exit_to_app_rounded,
      gradientStart: Color(0xFFC77DFF),
      gradientEnd: Color(0xFF7B2CBF),
      artKey: 'fakeCall',
      status: AppFeatureStatus.planned,
      details: 'This still needs scenario presets and one-tap trigger flows.',
    ),
    AppFeature(
      id: 'nearby_police',
      title: 'Nearby police stations',
      subtitle: 'Locate police stations on a map.',
      category: 'Nearby Help Features',
      icon: Icons.local_police_rounded,
      gradientStart: Color(0xFF8D6E63),
      gradientEnd: Color(0xFF5D4037),
      artKey: 'police',
      status: AppFeatureStatus.available,
      details: 'Nearby police screen exists with map-based placeholders and navigation.',
      routeName: '/nearby_police',
    ),
    AppFeature(
      id: 'nearby_hospitals',
      title: 'Nearby hospitals',
      subtitle: 'Find nearby medical support.',
      category: 'Nearby Help Features',
      icon: Icons.local_hospital_rounded,
      gradientStart: Color(0xFFF28482),
      gradientEnd: Color(0xFFD00000),
      artKey: 'police',
      status: AppFeatureStatus.planned,
      details: 'A nearby hospitals search flow still needs to be added.',
    ),
    AppFeature(
      id: 'nearby_safe_zones',
      title: 'Nearby safe zones',
      subtitle: 'Navigate to safe public points.',
      category: 'Nearby Help Features',
      icon: Icons.shield_rounded,
      gradientStart: Color(0xFF43AA8B),
      gradientEnd: Color(0xFF1B4332),
      artKey: 'police',
      status: AppFeatureStatus.planned,
      details: 'Safe-zone location discovery is not implemented yet.',
    ),
    AppFeature(
      id: 'nearby_emergency_services',
      title: 'Nearby emergency services',
      subtitle: 'Quick discoverability for urgent help.',
      category: 'Nearby Help Features',
      icon: Icons.emergency_rounded,
      gradientStart: Color(0xFFEF476F),
      gradientEnd: Color(0xFFB5179E),
      artKey: 'police',
      status: AppFeatureStatus.planned,
      details: 'This needs service aggregation and map search support.',
    ),
    AppFeature(
      id: 'women_council_access',
      title: 'Women council access',
      subtitle: 'Support center and council assistance.',
      category: 'Nearby Help Features',
      icon: Icons.diversity_3_rounded,
      gradientStart: Color(0xFFF15BB5),
      gradientEnd: Color(0xFFB5179E),
      artKey: 'helpline',
      status: AppFeatureStatus.planned,
      details: 'The concept exists in the repo, but it is not integrated into the main app flow yet.',
    ),
    AppFeature(
      id: 'rakshak_mode',
      title: 'Rakshak mode',
      subtitle: 'Guardian-help mode toggle.',
      category: 'Nearby Help Features',
      icon: Icons.volunteer_activism_rounded,
      gradientStart: Color(0xFFA47148),
      gradientEnd: Color(0xFF6F4518),
      artKey: 'helpline',
      status: AppFeatureStatus.partial,
      details: 'Rakshak Mode is available as a setting, but the full guardian workflow is still limited.',
      control: AppFeatureControl.rakshakMode,
    ),
    AppFeature(
      id: 'emergency_contacts_manager',
      title: 'Emergency contacts manager',
      subtitle: 'Add and manage your safety contacts.',
      category: 'Contacts / Network',
      icon: Icons.people_rounded,
      gradientStart: Color(0xFF4CC9F0),
      gradientEnd: Color(0xFF4361EE),
      artKey: 'contacts',
      status: AppFeatureStatus.available,
      details: 'Emergency contacts CRUD is already available.',
      routeName: '/contacts',
    ),
    AppFeature(
      id: 'family_live_tracking_access',
      title: 'Family live tracking access',
      subtitle: 'Allow guardians to watch your movement.',
      category: 'Contacts / Network',
      icon: Icons.family_restroom_rounded,
      gradientStart: Color(0xFF90CAF9),
      gradientEnd: Color(0xFF1D4ED8),
      artKey: 'contacts',
      status: AppFeatureStatus.partial,
      details: 'The data model supports contacts and journey watchers, but family tracking access is not a distinct experience yet.',
      routeName: '/safe_journey',
    ),
    AppFeature(
      id: 'trusted_guardians_list',
      title: 'Trusted guardians list',
      subtitle: 'Maintain your trusted people list.',
      category: 'Contacts / Network',
      icon: Icons.verified_user_rounded,
      gradientStart: Color(0xFFA9DEF9),
      gradientEnd: Color(0xFF3A86FF),
      artKey: 'contacts',
      status: AppFeatureStatus.partial,
      details: 'Contacts serve this role today, though guardian-specific roles are not separated yet.',
      routeName: '/contacts',
    ),
    AppFeature(
      id: 'quick_call_trusted_contact',
      title: 'Quick call trusted contact',
      subtitle: 'One-tap call to a trusted person.',
      category: 'Contacts / Network',
      icon: Icons.quick_contacts_dialer_rounded,
      gradientStart: Color(0xFF00F5D4),
      gradientEnd: Color(0xFF00B4D8),
      artKey: 'contacts',
      status: AppFeatureStatus.planned,
      details: 'A dedicated quick-call experience is not present yet.',
    ),
    AppFeature(
      id: 'sms_emergency_alerts',
      title: 'SMS emergency alerts',
      subtitle: 'Send direct SMS alerts to contacts.',
      category: 'Contacts / Network',
      icon: Icons.sms_rounded,
      gradientStart: Color(0xFF72EFDD),
      gradientEnd: Color(0xFF0077B6),
      artKey: 'contacts',
      status: AppFeatureStatus.planned,
      details: 'The package support exists, but the actual SMS dispatch workflow is not finished.',
    ),
    AppFeature(
      id: 'secret_audio_recording',
      title: 'Secret audio recording',
      subtitle: 'Capture background evidence audio.',
      category: 'Evidence & Security',
      icon: Icons.mic_rounded,
      gradientStart: Color(0xFFD291FF),
      gradientEnd: Color(0xFF9D4EDD),
      artKey: 'sos',
      status: AppFeatureStatus.partial,
      details: 'Audio recording exists and can auto-start during SOS, but not yet as a dedicated secret evidence mode.',
      control: AppFeatureControl.autoRecordAudio,
    ),
    AppFeature(
      id: 'secret_video_recording',
      title: 'Secret video recording',
      subtitle: 'Capture hidden evidence video.',
      category: 'Evidence & Security',
      icon: Icons.videocam_rounded,
      gradientStart: Color(0xFFE0AAFF),
      gradientEnd: Color(0xFF7B2CBF),
      artKey: 'sos',
      status: AppFeatureStatus.partial,
      details: 'Video recording exists and can auto-start during SOS, but not yet as a separate stealth recorder mode.',
      control: AppFeatureControl.autoRecordVideo,
    ),
    AppFeature(
      id: 'auto_evidence_capture',
      title: 'Auto evidence capture',
      subtitle: 'Collect evidence automatically on SOS.',
      category: 'Evidence & Security',
      icon: Icons.auto_awesome_motion_rounded,
      gradientStart: Color(0xFFFFC6FF),
      gradientEnd: Color(0xFFC77DFF),
      artKey: 'sos',
      status: AppFeatureStatus.partial,
      details: 'The app can auto-start audio/video capture on SOS depending on settings.',
      control: AppFeatureControl.autoRecordAudio,
    ),
    AppFeature(
      id: 'cloud_evidence_upload',
      title: 'Cloud evidence upload',
      subtitle: 'Back up safety evidence remotely.',
      category: 'Evidence & Security',
      icon: Icons.cloud_upload_rounded,
      gradientStart: Color(0xFFBDB2FF),
      gradientEnd: Color(0xFF5A189A),
      artKey: 'sos',
      status: AppFeatureStatus.planned,
      details: 'Cloud upload and secure transfer are not implemented yet.',
    ),
    AppFeature(
      id: 'secure_storage_evidence',
      title: 'Secure evidence storage',
      subtitle: 'Store recorded evidence safely.',
      category: 'Evidence & Security',
      icon: Icons.security_rounded,
      gradientStart: Color(0xFFB8C0FF),
      gradientEnd: Color(0xFF6D597A),
      artKey: 'sos',
      status: AppFeatureStatus.planned,
      details: 'The recordings exist, but there is no secure evidence vault UX yet.',
    ),
    AppFeature(
      id: 'location_timeline_logs',
      title: 'Location timeline logs',
      subtitle: 'Build a movement timeline for review.',
      category: 'Evidence & Security',
      icon: Icons.timeline_rounded,
      gradientStart: Color(0xFF9BF6FF),
      gradientEnd: Color(0xFF5E60CE),
      artKey: 'journey',
      status: AppFeatureStatus.planned,
      details: 'Timeline history storage and review UI are not finished yet.',
    ),
    AppFeature(
      id: 'women_safety_tips',
      title: 'Women safety tips',
      subtitle: 'Quick accessible practical guidance.',
      category: 'Women Safety Support',
      icon: Icons.tips_and_updates_rounded,
      gradientStart: Color(0xFFFFC300),
      gradientEnd: Color(0xFFFF8500),
      artKey: 'tips',
      status: AppFeatureStatus.available,
      details: 'Safety Tips screen is already available.',
      routeName: '/safety_tips',
    ),
    AppFeature(
      id: 'safety_education_articles',
      title: 'Safety education articles',
      subtitle: 'Long-form safety learning content.',
      category: 'Women Safety Support',
      icon: Icons.article_rounded,
      gradientStart: Color(0xFFFDE68A),
      gradientEnd: Color(0xFFF59E0B),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'The app currently includes tips, but not a full article library.',
    ),
    AppFeature(
      id: 'helpline_numbers',
      title: 'Helpline numbers',
      subtitle: 'Key support lines in one place.',
      category: 'Women Safety Support',
      icon: Icons.phone_in_talk_rounded,
      gradientStart: Color(0xFFFF8FAB),
      gradientEnd: Color(0xFFFB6F92),
      artKey: 'helpline',
      status: AppFeatureStatus.available,
      details: 'Helpline numbers are already shown on the women helpline screen.',
      routeName: '/women_helpline',
    ),
    AppFeature(
      id: 'women_helpline_access',
      title: 'Women helpline access',
      subtitle: 'Direct call access to support lines.',
      category: 'Women Safety Support',
      icon: Icons.support_agent_rounded,
      gradientStart: Color(0xFFFF5D8F),
      gradientEnd: Color(0xFFC9184A),
      artKey: 'helpline',
      status: AppFeatureStatus.available,
      details: 'Direct call actions are already implemented in the women helpline screen.',
      routeName: '/women_helpline',
    ),
    AppFeature(
      id: 'self_defense_guide',
      title: 'Self-defense quick guide',
      subtitle: 'Fast-access defense guidance.',
      category: 'Women Safety Support',
      icon: Icons.fitness_center_rounded,
      gradientStart: Color(0xFFFFA94D),
      gradientEnd: Color(0xFFFF6B35),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'A dedicated self-defense guide is not included yet.',
    ),
    AppFeature(
      id: 'login',
      title: 'Login',
      subtitle: 'Secure access to the app.',
      category: 'App / User Features',
      icon: Icons.login_rounded,
      gradientStart: Color(0xFF577590),
      gradientEnd: Color(0xFF2B2D42),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Login is implemented and connected to the backend.',
      routeName: '/login',
    ),
    AppFeature(
      id: 'signup',
      title: 'Signup',
      subtitle: 'Create a new account.',
      category: 'App / User Features',
      icon: Icons.person_add_alt_1_rounded,
      gradientStart: Color(0xFF84A59D),
      gradientEnd: Color(0xFF354F52),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Signup is implemented and connected to the backend.',
      routeName: '/signup',
    ),
    AppFeature(
      id: 'persistent_login_session',
      title: 'Persistent login session',
      subtitle: 'Stay signed in between launches.',
      category: 'App / User Features',
      icon: Icons.lock_clock_rounded,
      gradientStart: Color(0xFFA8DADC),
      gradientEnd: Color(0xFF457B9D),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Token persistence and session reload are already present.',
    ),
    AppFeature(
      id: 'profile_screen',
      title: 'Profile screen',
      subtitle: 'View and update user details.',
      category: 'App / User Features',
      icon: Icons.account_circle_rounded,
      gradientStart: Color(0xFFCAD2C5),
      gradientEnd: Color(0xFF52796F),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Profile screen is already available.',
      routeName: '/profile',
    ),
    AppFeature(
      id: 'settings_screen',
      title: 'Settings screen',
      subtitle: 'Control available app safety behavior.',
      category: 'App / User Features',
      icon: Icons.settings_rounded,
      gradientStart: Color(0xFFB0BEC5),
      gradientEnd: Color(0xFF607D8B),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Settings screen is already available.',
      routeName: '/settings',
    ),
    AppFeature(
      id: 'theme_mode',
      title: 'Theme mode',
      subtitle: 'Switch light and dark appearance.',
      category: 'App / User Features',
      icon: Icons.dark_mode_rounded,
      gradientStart: Color(0xFFBDE0FE),
      gradientEnd: Color(0xFF3A86FF),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'Theme mode is configurable in Settings.',
      control: AppFeatureControl.themeMode,
    ),
    AppFeature(
      id: 'premium_dashboard_ui',
      title: 'Premium dashboard UI',
      subtitle: 'Modern visual dashboard experience.',
      category: 'App / User Features',
      icon: Icons.dashboard_customize_rounded,
      gradientStart: Color(0xFF6C757D),
      gradientEnd: Color(0xFF343A40),
      artKey: 'profile',
      status: AppFeatureStatus.available,
      details: 'The dashboard has been upgraded to a richer product-style experience.',
      routeName: '/home',
    ),
    AppFeature(
      id: 'socketio_alerts',
      title: 'Socket.IO real-time alerts',
      subtitle: 'Live sockets for urgent events.',
      category: 'Smart Connectivity',
      icon: Icons.hub_rounded,
      gradientStart: Color(0xFF00B4D8),
      gradientEnd: Color(0xFF0077B6),
      artKey: 'liveLocation',
      status: AppFeatureStatus.available,
      details: 'Socket service is already integrated in the frontend and backend.',
    ),
    AppFeature(
      id: 'mongodb_storage',
      title: 'MongoDB user data storage',
      subtitle: 'Persist user and safety data.',
      category: 'Smart Connectivity',
      icon: Icons.storage_rounded,
      gradientStart: Color(0xFF52B788),
      gradientEnd: Color(0xFF2D6A4F),
      artKey: 'contacts',
      status: AppFeatureStatus.available,
      details: 'MongoDB Atlas-backed user data storage is already in use on the backend.',
    ),
    AppFeature(
      id: 'realtime_notifications',
      title: 'Real-time notifications',
      subtitle: 'Prompt users with ongoing safety updates.',
      category: 'Smart Connectivity',
      icon: Icons.notifications_active_rounded,
      gradientStart: Color(0xFFFFD166),
      gradientEnd: Color(0xFFEF476F),
      artKey: 'journey',
      status: AppFeatureStatus.partial,
      details: 'Local notifications exist for check-ins, but richer real-time alert delivery is still incomplete.',
      control: AppFeatureControl.notifications,
    ),
    AppFeature(
      id: 'backend_node_api',
      title: 'Backend Node.js API support',
      subtitle: 'API-driven mobile safety backend.',
      category: 'Smart Connectivity',
      icon: Icons.api_rounded,
      gradientStart: Color(0xFF4361EE),
      gradientEnd: Color(0xFF1D3557),
      artKey: 'contacts',
      status: AppFeatureStatus.available,
      details: 'Node.js backend routes for auth, contacts, SOS, location, and journey already exist.',
    ),
    AppFeature(
      id: 'biometric_unlock',
      title: 'Biometric unlock',
      subtitle: 'Protect entry with device biometrics.',
      category: 'Future Features',
      icon: Icons.fingerprint_rounded,
      gradientStart: Color(0xFFD291FF),
      gradientEnd: Color(0xFF7B2CBF),
      artKey: 'profile',
      status: AppFeatureStatus.planned,
      details: 'Dependency support exists, but biometric UX is not integrated yet.',
    ),
    AppFeature(
      id: 'qr_safety_sharing',
      title: 'QR safety sharing',
      subtitle: 'Share safety info via QR code.',
      category: 'Future Features',
      icon: Icons.qr_code_2_rounded,
      gradientStart: Color(0xFFA9DEF9),
      gradientEnd: Color(0xFF3A86FF),
      artKey: 'contacts',
      status: AppFeatureStatus.planned,
      details: 'QR package support exists, but the feature flow is not integrated yet.',
    ),
    AppFeature(
      id: 'community_concern_reporting',
      title: 'Community concern reporting',
      subtitle: 'Report area or community safety concerns.',
      category: 'Future Features',
      icon: Icons.report_problem_rounded,
      gradientStart: Color(0xFFFF7B7B),
      gradientEnd: Color(0xFFD90429),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'Concern reporting is not yet part of the current app flow.',
    ),
    AppFeature(
      id: 'raise_concern_mode',
      title: 'Raise concern mode',
      subtitle: 'Structured concern escalation flow.',
      category: 'Future Features',
      icon: Icons.flag_rounded,
      gradientStart: Color(0xFFFFA62B),
      gradientEnd: Color(0xFFFF595E),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'A concern screen exists elsewhere in the repo, but it is not integrated in the main app routes.',
    ),
    AppFeature(
      id: 'anonymous_incident_report',
      title: 'Anonymous incident report',
      subtitle: 'Submit an incident without identity exposure.',
      category: 'Future Features',
      icon: Icons.person_off_rounded,
      gradientStart: Color(0xFF9381FF),
      gradientEnd: Color(0xFF5E548E),
      artKey: 'tips',
      status: AppFeatureStatus.planned,
      details: 'This needs dedicated forms, moderation, and privacy-safe backend support.',
    ),
    AppFeature(
      id: 'smart_wearable_integration',
      title: 'Smart wearable integration',
      subtitle: 'Trigger safety flows from wearables.',
      category: 'Future Features',
      icon: Icons.watch_rounded,
      gradientStart: Color(0xFF95D5B2),
      gradientEnd: Color(0xFF40916C),
      artKey: 'journey',
      status: AppFeatureStatus.planned,
      details: 'No wearable integration exists yet.',
    ),
  ];

  static List<AppFeature> byCategory(String category) =>
      all.where((feature) => feature.category == category).toList();

  static List<AppFeature> controllableInSettings() =>
      all.where((feature) => feature.control != null).toList();
}
